// leave off @2x/@3x
const images = {
  logo: require('../Images/hp-logo.png'),
  gps: require('../Images/gps.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/bgHP.jpg'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  profileIcon: require('../Images/Icons/profile-icon.png'),
  helpIcon: require('../Images/Icons/help.png'),
  historyIcon: require('../Images/Icons/history.png'),
  homeIcon: require('../Images/Icons/home.png'),
  settingsIcon: require('../Images/Icons/settings.png'),
  favouriteIcon: require('../Images/Icons/star.png'),
  userIcon: require('../Images/Icons/user.png'),
  houseImage: require('../Images/house.jpg'),
  fullStarIcon: require('../Images/Icons/full-star.png'),
  starLines: require('../Images/Icons/star-line.png'),
  logo1: require('../Images/logo1.png'),
  login: require('../Images/login.png'),
  camara: require('../Images/camara.png'),
  greenStar: require('../Images/Icons/full-star-green.png'),
  greenStarLines: require('../Images/Icons/star-line-green.png') 
};

export default images
